name: simple_live_app
version: 1.8.4+10804
publish_to: none
description: "Slive APP"
environment: 
  sdk: '>=3.0.5 <4.0.0'
  flutter: 3.38.4

dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

  simple_live_core:
    path: ../simple_live_core
  # 图标
  cupertino_icons: ^1.0.8
  remixicon: ^1.4.1 # Remix 图标

  # 框架、工具
  archive: ^4.0.7 # 文件压缩
  get: ^4.7.2 # 状态管理、路由管理、国际化
  dio: ^5.4.3+1 # 网络请求
  hive: 2.2.3 # 持久化存储
  hive_flutter: 1.1.0 # 持久化存储
  logger: ^2.0.2 # 日志
  intl: ^0.20.2 # 国际化
  qr_flutter: ^4.1.0 # 二维码生成
  dynamic_color: ^1.8.1 # 动态颜色
  path: any
  udp: ^5.0.3 # UDP
  uuid: ^4.5.1 # UUID
  synchronized: ^3.3.1 # 线程安全
  collection: ^1.18.0
  pool: ^1.5.2 #并发控制器

  # Widget
  flutter_staggered_grid_view: ^0.7.0 # 瀑布流 / GridView
  flutter_easyrefresh: 2.2.2 # 下拉刷新、上拉加载
  extended_image: ^10.0.1 # 拓展 Image ，支持缓存
  flutter_smart_dialog: ^4.9.8+9 # 各种弹窗 Toast / Dialog / Popup
  sticky_headers: ^0.3.0+2 # 吸顶
  lottie: ^3.3.2 # Lottie 动画
  canvas_danmaku: ^0.2.7 # 弹幕库

  # 系统交互
  package_info_plus: ^8.3.1 # 包信息
  device_info_plus: ^12.2.0 # 设备信息
  url_launcher: ^6.3.1 # 打开链接
  share_plus: ^12.0.1 # 分享
  path_provider: ^2.1.3 # 常用路径
  cross_file: ^0.3.5+1 # 跨平台文件
  # permission_handler: ^12.0.1 # 权限处理
  permission_handler_apple: ^9.4.7
  permission_handler_android: ^13.0.1
  permission_handler_platform_interface: ^4.3.0
  flutter_image_gallery_saver: ^0.0.2 # 图片保存到相册
  screen_brightness: ^2.1.7 # 亮度控制
  auto_orientation_v2: ^2.3.6 # 屏幕方向
  wakelock_plus: ^1.3.3 # 屏幕常亮
  file_picker: ^10.1.2 # 文件选择
  window_manager: ^0.5.0 # 窗口管理
  floating: ^6.0.0 # PIP 画中画
  flutter_inappwebview:
    git:
      url: https://github.com/guide-inc-org/guide-flutter_inappwebview.git
      path: flutter_inappwebview
      ref: sbi_fx_pc/v6.2.0-beta.3
  connectivity_plus: ^7.0.0 # 网络状态
  flutter_single_instance: ^1.7.0 # 应用启动检测
  qr_code_scanner_plus: ^2.0.14 # 二维码扫描

  # 网络相关
  webdav_client: ^1.2.2 # WebDAV
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  network_info_plus: ^7.0.0
  signalr_netcore: ^1.3.9 # SignalR

  # 视频播放
  volume_controller: any
  media_kit:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: 66d46c3d77ee15684e0c5c6ed51ac78d819d5e6f
      path: ./media_kit
  media_kit_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: 66d46c3d77ee15684e0c5c6ed51ac78d819d5e6f
      path: ./media_kit_video
  media_kit_libs_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: 66d46c3d77ee15684e0c5c6ed51ac78d819d5e6f
      path: ./libs/universal/media_kit_libs_video
  rust_lib_simple_live_app:
    path: rust_builder
  flutter_rust_bridge: 2.11.1

dependency_overrides:
  media_kit_libs_linux:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: 66d46c3d77ee15684e0c5c6ed51ac78d819d5e6f
      path: ./libs/linux/media_kit_libs_linux
  media_kit_libs_ios_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: 66d46c3d77ee15684e0c5c6ed51ac78d819d5e6f
      path: ./libs/ios/media_kit_libs_ios_video
  media_kit_libs_android_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: 66d46c3d77ee15684e0c5c6ed51ac78d819d5e6f
      path: ./libs/android/media_kit_libs_android_video
  media_kit_libs_windows_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: 66d46c3d77ee15684e0c5c6ed51ac78d819d5e6f
      path: ./libs/windows/media_kit_libs_windows_video
  media_kit_libs_macos_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: 66d46c3d77ee15684e0c5c6ed51ac78d819d5e6f
      path: ./libs/macos/media_kit_libs_macos_video

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_test: 
    sdk: flutter
  integration_test:
    sdk: flutter

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/logo.png"

flutter: 
  uses-material-design: true
  assets:
    - assets/statement.txt
    - assets/images/
    - assets/icons/
    - assets/lotties/
    - shorebird.yaml
