name: simple_live_app
version: 1.11.2+11102
publish_to: none
description: "Simple Live APP"
environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  simple_live_core:
    path: ../simple_live_core
  # 图标
  cupertino_icons: ^1.0.8
  remixicon: ^1.4.1 #Remix图标

  # 框架、工具
  get: ^4.7.3 #状态管理、路由管理、国际化
  dio: ^5.9.0 #网络请求
  hive: 2.2.3 #持久化存储
  hive_flutter: 1.1.0 #持久化存储
  logger: ^2.6.2 #日志
  intl: ^0.20.2 #国际化
  qr_flutter: ^4.1.0 #二维码生成
  dynamic_color: ^1.8.1 #动态颜色
  path: any
  collection: any
  udp: ^5.0.3 #UDP
  uuid: ^4.5.2 #UUID
  webdav_client: ^1.2.2 # WebDAV
  archive: ^4.0.7 #文件压缩
  crypto: ^3.0.7

  #Widget
  flutter_staggered_grid_view: ^0.7.0 #瀑布流/GridView
  flutter_easyrefresh: 2.2.2 #下拉刷新、上拉加载
  extended_image: ^10.0.1 #拓展Image,支持缓存
  flutter_smart_dialog: ^4.9.8+9 #各种弹窗 Toast/Dialog/Popup
  sticky_headers: ^0.3.0+2 #吸顶
  lottie: ^3.3.2 #lottie动画
  canvas_danmaku: ^0.2.7
  # ns_danmaku: #弹幕
  #   git:
  #     url: https://github.com/xiaoyaocz/flutter_ns_danmaku.git
  #     tag: v0.0.9

  #系统交互
  package_info_plus: ^9.0.0 #包信息
  device_info_plus: ^12.2.0 #设备信息
  url_launcher: ^6.3.2 #打开链接
  share_plus: ^12.0.1 #分享
  path_provider: ^2.1.5 #常用路径
  cross_file: ^0.3.5 #跨平台文件
  permission_handler: ^12.0.1 #权限处理
  image_gallery_saver_plus: ^4.0.1 #图片保存到相册
  screen_brightness: ^2.1.7 #亮度控制
  auto_orientation_v2: ^2.3.6 #屏幕方向
  wakelock_plus: ^1.4.0 #屏幕常亮
  file_picker: ^10.3.7 #文件选择
  window_manager: ^0.5.1 #窗口管理
  floating: ^6.0.0 #PIP画中画
  flutter_inappwebview: ^6.1.5 #WebView
  connectivity_plus: ^7.0.0 #网络状态
  qr_code_scanner_plus: ^2.0.14 #二维码扫描
  volume_controller: ^3.4.0 #音量控制

  # 网络相关
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  network_info_plus: ^7.0.0
  signalr_netcore: ^1.4.4 #SignalR

  # 视频播放
  media_kit: ^1.2.2
  media_kit_video: ^2.0.0
  media_kit_libs_video: ^1.0.7

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  macos:
    generate: true

flutter:
  uses-material-design: true
  assets:
    - assets/statement.txt
    - assets/images/
    - assets/icons/
    - assets/lotties/
