display_name: Slive
app_id: 45F6FA98-DA23-4795-8685-60F607317A1F
publisher: slotsun
publisher_url: https://github.com/fastforgedev/fastforge
create_desktop_icon: true
# See: https://jrsoftware.org/ishelp/index.php?topic=setup_defaultdirname
install_dir_name: "D:\\Program Files (x86)\\simple_live"
# 这里的路径是相对于项目根目录的路径； 图标格式必须是ico格式，不能是png或其它
setup_icon_file: assets/icons/app_icon.ico
locales:
  - en
  - zh