name: simple_live_core
version: 1.0.4
description: "聚合直播核心库"
repository: https://github.com/xiaoyaocz/dart_simple_live
publish_to: "none"
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.5.0+1
  logger: ^2.4.0
  web_socket_channel: ^3.0.1
  html_unescape: ^2.0.0
  protobuf: ^4.1.0
  crypto: ^3.0.3
  brotli: ^0.6.0
  tars_dart:
    path: ./packages/tars_dart
  fixnum: ^1.1.0
  flutter_qjs:
    git:
      url: https://github.com/wgh136/flutter_qjs.git
      branch: master
  dart_sm: ^0.1.5

dev_dependencies: 
  lints: ^6.0.0
  test: ^1.21.0

flutter:
  assets:
    - assets/js/douyin-webmssdk.js
