name: simple_live_console
description: A sample command-line application.
version: 1.0.0
publish_to: "none"
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  simple_live_core:
    path: ../simple_live_core

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
