name: app-build-action-dev

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'

# If previous workflow is still running, we push again, we will cancel the previous workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  # æ‰“åŒ… Androidã€iOSã€Mac
  build-mac-ios-android:
    # https://github.com/actions/runner-images/issues/12541
    runs-on: macos-15

    permissions:
      contents: write

    steps:
      # ç­¾å‡ºä»£ç 
      - uses: actions/checkout@v4
        with:
          ref: dev

      # APK ç­¾åè®¾ç½®
      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: keystore.jks
          encodedString: ${{ secrets.KEYSTORE_BASE64 }}
      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > simple_live_app/android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> simple_live_app/android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> simple_live_app/android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> simple_live_app/android/key.properties

      # è®¾ç½® JAVA ç¯å¢ƒ
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: "21"
          cache: "gradle"

      # è®¾ç½® Flutter
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version-file: simple_live_app/pubspec.yaml
          cache: true 

      # æ‰“å¼€ MAC Desktop æ”¯æŒ
      - name: Enable Flutter Desktop
        run: flutter config --enable-macos-desktop

      # æ›´æ–° Flutter çš„ packages
      - name: Restore packages
        run: |
          cd simple_live_app
          flutter pub get

      # å®‰è£… appdmg npm install -g appdmg
      - name: Install appdmg
        run: npm install -g appdmg

      # è®¾ç½® Fastforge ç¯å¢ƒ
      - name: Install fast-forge
        run: | 
          git clone https://github.com/SlotSun/fastforge.git
          cd fastforge
          dart pub global activate melos
          melos run activate

      # æ‰“åŒ… APK
      - name: Build APK
        run: |
          cd simple_live_app
          flutter build apk --release --split-per-abi

      # ä¸Šä¼  Artifacts
      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android
          path: |
            simple_live_app/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            simple_live_app/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            simple_live_app/build/app/outputs/flutter-apk/app-x86_64-release.apk

      # æ‰“åŒ… iOS
      - name: Build IPA
        run: |
          cd simple_live_app
          flutter build ios --release --no-codesign

      # åˆ›å»ºæœªç­¾å ipa
      - name: Create IPA
        run: |
          cd simple_live_app
          mkdir build/ios/iphoneos/Payload
          cp -R build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/Runner.app
          cd build/ios/iphoneos/
          zip -q -r ios_no_sign.ipa Payload
          cd ../../..

      # ä¸Šä¼  IPA è‡³ Artifacts
      - name: Upload IPA to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios
          path: |
            simple_live_app/build/ios/iphoneos/ios_no_sign.ipa

      # æ‰“åŒ… MAC
      - name: Build MacOS
        run: |
          cd simple_live_app
          fastforge package --platform macos --targets dmg,zip --skip-clean
      
      # ä¸Šä¼  MAC è‡³ Artifacts
      - name: Upload MacOS to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mac
          path: |
            simple_live_app/build/dist/*/*.dmg
            simple_live_app/build/dist/*/*.zip
      # å®Œæˆ
      - run: echo "ğŸ This job's status is ${{ job.status }}."

  # æ‰“åŒ… Linux
  build-linux:
    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04
            arch: x86_64
          - runner: ubuntu-24.04-arm
            arch: aarch64
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: write
    steps:
      # ç­¾å‡ºä»£ç 
      - uses: actions/checkout@v4
        with:
          ref: dev
      # è®¾ç½® Flutter ç¯å¢ƒ
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version-file: simple_live_app/pubspec.yaml
          channel: master
      # å®‰è£…ä¾èµ–
      - name: Update apt-get
        run: sudo apt-get update
      - name: Install Dependencies
        run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libmpv-dev mpv libasound2-dev
      # æ‰“å¼€ Linux Desktop æ”¯æŒ
      - name: Enable Flutter Desktop
        run: flutter config --enable-linux-desktop
      # æ›´æ–° Flutter çš„ packages
      - name: Restore Packages
        run: |
          cd simple_live_app
          flutter pub get
      # è®¾ç½® Fastforge ç¯å¢ƒ
      - name: Install fast-forge
        run: |
          git clone https://github.com/SlotSun/fastforge.git
          cd fastforge
          dart pub global activate melos
          melos run activate
      # build Linux DEB \ ZIP
      - name: Build Linux
        run: |
          cd simple_live_app
          fastforge package --platform linux --targets deb,zip --skip-clean
          cd build/dist/*
          mv simple_live_app-*-linux.deb Slive-${{ matrix.arch }}-linux.deb
          mv simple_live_app-*-linux.zip Slive-${{ matrix.arch }}-linux.zip
      # ä¸Šä¼  Linux åŒ…è‡³ Artifacts
      - name: Upload Linux APP to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.arch }}
          path: |
            simple_live_app/build/dist/*/*.deb
            simple_live_app/build/dist/*/*.zip

      # å®Œæˆ
      - run: echo "ğŸ Linux job's status is ${{ job.status }}."

  # æ‰“åŒ… Windows
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      # ç­¾å‡ºä»£ç 
      - uses: actions/checkout@v4
        with:
          ref: dev
      # è®¾ç½® Flutter ç¯å¢ƒ
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version-file: simple_live_app/pubspec.yaml
          cache: true
      - name: Enable Flutter Desktop
        run: flutter config --enable-windows-desktop
      - name: Restore Packages
        run: |
          cd simple_live_app
          flutter clean
          flutter pub get
      # è®¾ç½® Fastforge ç¯å¢ƒ å’Œ Inno Setup
      - name: Install fast-forge and Inno Setup
        run: |
          git clone https://github.com/SlotSun/fastforge.git
          cd fastforge
          dart pub global activate melos
          melos run activate
          choco install innosetup
      # æ·»åŠ ä¸­æ–‡å®‰è£…å¼•å¯¼
      - name: Add Chinese language file for Inno Setup
        run: |
          cd simple_live_app
          Copy-Item "windows/packaging/exe/ChineseSimplified.isl" "C:\Program Files (x86)\Inno Setup 6\Languages\ChineseSimplified.isl"
        shell: powershell
      # build Windows ZIP\MSIX\EXE
      - name: Build Windows
        run: |
          cd simple_live_app
          fastforge package --platform windows --targets msix,zip,exe --skip-clean
          Get-ChildItem "simple_live_app-*" | ForEach-Object {
              $newName = $_.Name -replace '^simple_live_app', 'Slive'
              Rename-Item $_ -NewName $newName
          }
        shell: pwsh
      # ä¸Šä¼  Windows è‡³ Artifacts
      - name: Upload Windows APP to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: |
            simple_live_app/build/dist/*/*.msix
            simple_live_app/build/dist/*/*.zip
            simple_live_app/build/dist/*/*.exe
      # å®Œæˆ
      - run: echo "ğŸ Windows job's status is ${{ job.status }}."

  # æ‰“åŒ… Flatpak
  build-flatpak:
    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04
            arch: x86_64
          - runner: ubuntu-24.04-arm
            arch: aarch64
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: write
    steps:
      # ç­¾å‡ºä»£ç 
      - uses: actions/checkout@v4
        with:
          ref: dev
      # å®‰è£…ä¾èµ–
      - name: Install dependencies
        run: |
          sudo add-apt-repository -y ppa:flatpak/stable
          sudo apt-get update -q
          sudo apt-get install -y flatpak flatpak-builder ca-certificates gnupg software-properties-common
          flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo
          git config --global protocol.file.allow always
      # æ„å»º Flatpak bundle
      - name: Build flatpak bundle
        run: |
          flatpak-builder build-dir flatpak/flatpak-manifest.yaml \
            --arch=${{ matrix.arch }} \
            --repo=${{ matrix.arch }} \
            --force-clean \
            --user \
            --install-deps-from=flathub \
            --ccache \
            --disable-rofiles-fuse
          flatpak build-bundle ${{ matrix.arch }} Slive-${{ matrix.arch }}.flatpak io.github.SlotSun.dart_simple_live

      # ä¸Šä¼  Flatpak åŒ…è‡³ Artifacts
      - name: Upload linux flatpak to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-flatpak-${{ matrix.arch }}
          path: Slive-*.flatpak

      # å®Œæˆ
      - run: echo "ğŸ Flatpak job's status is ${{ job.status }}."
